import { TDeps } from "../deps";
import { TOutputTransformer } from ".";
import { join } from "path";

export const infoOutputTransformer: TOutputTransformer = (output, deps) => {
  const version = getPackageVersion(deps);
  return generateInfo(version, output);
};

export function generateInfo(version: string, output: string): string {
  return [
    `/* Generated by ts-generator ver. ${version} */`,
    "/* tslint:disable */",
    "/* eslint-disable */",
    output,
  ].join("\n");
}

function getPackageVersion({ fs }: TDeps): string {
  const packageJsonPath = join(__dirname, "../../package.json");

  return JSON.parse(fs.readFileSync(packageJsonPath, "utf8")).version || "UNKNOWN";
}
