exports['integration should run ts-gen programmatically 1'] = `
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export const name: string;
export const age: number;

`

exports['integration should run ts-gen programmatically 2'] = `
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export default "after";

`

exports['integration should run ts-gen programmatically 3'] = `
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export default "before";

`
