exports['integration should run ts-gen programmatically 1'] = `
/* Generated by ts-generator ver. 1.0.0 */
/* tslint:disable */
export const name: string;
export const age: number;

`

exports['integration should run ts-gen programmatically 2'] = `
/* Generated by ts-generator ver. 1.0.0 */
/* tslint:disable */
export default "after";

`

exports['integration should run ts-gen programmatically 3'] = `
/* Generated by ts-generator ver. 1.0.0 */
/* tslint:disable */
export default "before";

`
